version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    hostname: mongodb
    container_name: fiware-mongodb
    ports:
      - "27017:27017"
    command: --nojournal
    volumes:
      - mongodb_data:/data/db
    networks:
      - fiware

  orion:
    image: fiware/orion:3.10.1
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongodb
    ports:
      - "1026:1026"
    command: -dbhost mongodb -logLevel DEBUG
    networks:
      - fiware

  mosquitto:
    image: eclipse-mosquitto:2.0
    hostname: mosquitto
    container_name: fiware-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
    networks:
      - fiware

  iot-agent:
    image: fiware/iotagent-mqtt:2.4.0
    hostname: iot-agent
    container_name: fiware-iot-agent
    depends_on:
      - mongodb
      - mosquitto
      - orion
    ports:
      - "4041:4041"
    environment:
      - IOTA_CB_HOST=orion
      - IOTA_CB_PORT=1026
      - IOTA_NORTH_PORT=4041
      - IOTA_REGISTRY_TYPE=mongodb
      - IOTA_MONGO_HOST=mongodb
      - IOTA_MONGO_PORT=27017
      - IOTA_MONGO_DB=iotagent
      - IOTA_MQTT_HOST=mosquitto
      - IOTA_MQTT_PORT=1883
      - IOTA_PROVIDER_URL=http://iot-agent:4041
    networks:
      - fiware

volumes:
  mongodb_data:
  mosquitto_data:

networks:
  fiware:
    driver: bridge
